name: quelea
version: '2024.0'
base: core18
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.
confinement: strict

environment:
    JAVA_HOME: $SNAP/usr/lib/jvm/default-java
    PATH: $SNAP/usr/lib/jvm/default-java/bin:$PATH
    
architectures:
  - build-on: [amd64]

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, mount-observe, network-control, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media, gsettings, account-control]

parts:
  quelea:
    plugin: gradle
    source: Quelea
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
    build-packages: [default-jre, openjfx, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-tools, gstreamer1.0-x, gstreamer1.0-alsa, gstreamer1.0-gl, gstreamer1.0-gtk3, gstreamer1.0-qt5, gstreamer1.0-pulseaudio, zlib1g, zlib1g-dev]
    stage-packages: [default-jre, openjfx, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-tools, gstreamer1.0-x, gstreamer1.0-alsa, gstreamer1.0-gl, gstreamer1.0-gtk3, gstreamer1.0-qt5, gstreamer1.0-pulseaudio, zlib1g, zlib1g-dev]
    gradle-openjdk-version: "11"
    gradle-options: [--debug, -Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar, copyToDist]
    gradle-output-dir: 'dist'
